title: Onur Inan
author: Onur Inan
email: onur.inan.h@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Cyber Security
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.onurinan.nl" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  honour50
# twitter_username: jekyllrb

# Build settings
# theme: no-style-please
remote_theme: no-style-please
plugins:
  - jekyll-feed
  # - jekyll-seo-tag

theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%m-%d-%Y"
  show_description: false

sass:
  style: :compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
